version: 2.1

orbs:
    node: circleci/node@5.0.2

jobs:
    build_and_test:
        executor: node/default
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: npm
            - run:
                  command: npm run test
                  name: Run tests
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - .
    publish:
        executor: node/default
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run:
                  name: Authenticate with npm
                  command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
            - run:
                  name: Publish
                  command: npm run publish:latest

workflows:
    build:
        jobs:
            - build_and_test
            - publish:
                  requires:
                      - build_and_test
                  filters:
                      branches:
                          only:
                              - main
